version: "3"
services:
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    container_name: app_backend
    ports:
      - "3000:3000"
